"""Fix is_2fa_enabled to be non-nullable

Revision ID: 40b1d0fa0bcf
Revises: ce5b9e41091e
Create Date: 2025-05-29 01:09:12.548305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b1d0fa0bcf'
down_revision = 'ce5b9e41091e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
