"""add 2FA fields

Revision ID: ce5b9e41091e
Revises: 
Create Date: 2025-05-29 00:43:29.378957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5b9e41091e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_fa_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_fa_secret')
        batch_op.drop_column('is_2fa_enabled')

    # ### end Alembic commands ###
